- name: Preconfig
  hosts: Server
  tasks:
    - name: Install Docker
      block:
        - name: Add universe distr
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present

        - name: Install additional package
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl 
              - gnupg
              - lsb-release
            update-cache: yes
            cache_valid_time: 86400
        - name: Add key Docker
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name:  Install stable repository
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable 
            state: present
            update-cache: yes
            filename: docker
        - name: Install docker 
          apt:
            name: docker.io
            state: latest
            update-cache: yes
        - name: Check install Docker and reboot
          service:
            name: docker
            state: restarted
            enabled: yes
      become: yes
   